### ISSUE TITLE
crash on netbook

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#153]
Setup assistant UI doesn't fit on my netbook. Also, it crashes after hitting Load on the first page, here's the tail of the debug output
#10 0xb7fbaab9 in moveit_setup_assistant::SetupAssistantWidget::progressPastStartScreen() ()

   from /home/rwilson/moveit/devel/lib/libmoveit_setup_assistant_widgets.so
(gdb) down
#9  0xb7f99b6d in moveit_setup_assistant::RobotPosesWidget::RobotPosesWidget(QWidget*, boost::shared_ptr<moveit_setup_assistant::MoveItConfigData>) () from /home/rwilson/moveit/devel/lib/libmoveit_setup_assistant_widgets.so

(gdb)
#8  0xb6ce96e3 in moveit_setup_assistant::MoveItConfigData::getPlanningScene() ()

   from /home/rwilson/moveit/devel/lib/libmoveit_setup_assistant_tools.so
(gdb)
#7  0xb6b2bdc8 in planning_scene::PlanningScene::configure(boost::shared_ptr<urdf::ModelInterface const> const&, boost::shared_ptr<srdf::Model const> const&, boost::shared_ptr<kinematic_model::KinematicModel> const&) ()

   from /home/rwilson/moveit/devel/lib/libmoveit_planning_scene.so
(gdb)
#6  0xb6b395b8 in planning_scene::PlanningScene::CollisionDetectionAlloc<collision_detection::CollisionWorldFCL, collision_detection::CollisionRobotFCL>::allocateRobot(boost::shared_ptr<kinematic_model::KinematicModel const> const&) () from /home/rwilson/moveit/devel/lib/libmoveit_planning_scene.so

(gdb)
#5  0xb5f9a62e in collision_detection::CollisionRobotFCL::CollisionRobotFCL(boost::shared_ptr<kinematic_model::KinematicModel const> const&, double, double) ()

   from /home/rwilson/moveit/devel/lib/libmoveit_collision_detection_fcl.so
(gdb)
#4  0xb5f92b22 in collision_detection::createCollisionGeometry(boost::shared_ptr<shapes::Shape const> const&, double, double, kinematic_model::LinkModel const*) ()

   from /home/rwilson/moveit/devel/lib/libmoveit_collision_detection_fcl.so
(gdb)
#3  0xb5f99100 in boost::shared_ptr<collision_detection::FCLGeometry const> collision_detection::createCollisionGeometry<fcl::OBBRSS, kinematic_model::LinkModel>(boost::shared_ptr<shapes::Shape const> const&, double, double, kinematic_model::LinkModel const*) () from /home/rwilson/moveit/devel/lib/libmoveit_collision_detection_fcl.so

(gdb)
#2  0xb5f98bd0 in boost::shared_ptr<collision_detection::FCLGeometry const> collision_detection::createCollisionGeometry<fcl::OBBRSS, kinematic_model::LinkModel>(boost::shared_ptr<shapes::Shape const> const&, kinematic_model::LinkModel const*) () from /home/rwilson/moveit/devel/lib/libmoveit_collision_detection_fcl.so

(gdb)
#1  0xb4956101 in fcl::BVHModelfcl::OBBRSS::endModel() () from /opt/ros/groovy/lib/libfcl.so

(gdb)
#0  0xb4955d49 in fcl::BVHModelfcl::OBBRSS::buildTree() () from /opt/ros/groovy/lib/libfcl.so

(gdb)
Bottom (innermost) frame selected; you cannot go down.
(gdb)

**Comment by isucan** [comment]
I am going to blame this on the reduced instruction set of the cpu. Will reopen if needed.
