### ISSUE TITLE
Segfault in moveit_run_benchmark

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#233]
After running a set of benchmarks the program segfaults in its deconstructors. I can't track down what the problem is but it starts in KinematicsBase:

GDB Output:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff00178bc in boost::detail::sp_counted_impl_p<kinematics::KinematicsBase>::dispose() ()
   from /home/dave/ros/moveit/devel/lib/libmoveit_kinematics_plugin_loader.so
(gdb) bt
#0  0x00007ffff00178bc in boost::detail::sp_counted_impl_p<kinematics::KinematicsBase>::dispose() ()
   from /home/dave/ros/moveit/devel/lib/libmoveit_kinematics_plugin_loader.so
#1  0x00007ffff3ee2b4a in robot_model::JointModelGroup::~JointModelGroup() () from /home/dave/ros/moveit/devel/lib/libmoveit_robot_model.so
#2  0x00007ffff3eec5e1 in robot_model::RobotModel::~RobotModel() () from /home/dave/ros/moveit/devel/lib/libmoveit_robot_model.so
#3  0x00007ffff3eeca29 in robot_model::RobotModel::~RobotModel() () from /home/dave/ros/moveit/devel/lib/libmoveit_robot_model.so
#4  0x00007fffcbdcb91a in ompl_interface::ModelBasedStateSpace::~ModelBasedStateSpace() () from /home/dave/ros/moveit/devel/lib/libmoveit_ompl_interface.so
#5  0x00007fffcbdcef67 in ompl_interface::JointModelStateSpace::~JointModelStateSpace() () from /home/dave/ros/moveit/devel/lib/libmoveit_ompl_interface.so
#6  0x00007fffcb98596a in ompl::base::SpaceInformation::~SpaceInformation() () from /opt/ros/groovy/lib/libompl.so.6
#7  0x00007fffcba94d62 in boost::detail::sp_counted_impl_p<ompl::tools::SelfConfig::SelfConfigImpl>::dispose() () from /opt/ros/groovy/lib/libompl.so.6
#8  0x00007fffcba95119 in std::_Rb_tree<ompl::base::SpaceInformation*, std::pair<ompl::base::SpaceInformation* const, boost::shared_ptr<ompl::tools::SelfConfig::SelfConfigImpl> >, std::_Select1st<std::pair<ompl::base::SpaceInformation* const, boost::shared_ptr<ompl::tools::SelfConfig::SelfConfigImpl> > >, std::less<ompl::base::SpaceInformation*>, std::allocator<std::pair<ompl::base::SpaceInformation* const, boost::shared_ptr<ompl::tools::SelfConfig::SelfConfigImpl> > > >::_M_erase(std::_Rb_tree_node<std::pair<ompl::base::SpaceInformation* const, boost::shared_ptr<ompl::tools::SelfConfig::SelfConfigImpl> > >*) ()
   from /opt/ros/groovy/lib/libompl.so.6
#9  0x00007ffff632f901 in __run_exit_handlers (status=0, listp=0x7ffff66ac688, run_list_atexit=true) at exit.c:78
#10 0x00007ffff632f985 in __GI_exit (status=<optimized out>) at exit.c:100
#11 0x00007ffff6315774 in __libc_start_main (main=0x40d5e0 <main>, argc=5, ubp_av=0x7fffffffd888, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffd878) at libc-start.c:258
#12 0x000000000040e19d in _start ()
```

**Comment by isucan** [comment]
This is an order of destruction problem caused by some caching of shared ptrs in OMPL. This was changed to weak ptrs to avoid the problem.

**Comment by toliver** [comment]
I seem to be having the same problem. I am using the latest hydro released version.

```
ros-hydro-moveit-core                        0.5.6-0precise-20140206-2134-+0000
ros-hydro-ompl                               0.13.0002516-0precise-20130806-1107-+0000
```

Is this supposed to be solved in these hydro releases, or it's just a matter of waiting for the next release?

GDB output:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff62b8e2c in boost::detail::sp_counted_impl_p<kinematics::KinematicsBase>::dispose() () from /opt/ros/hydro/lib/libmoveit_kinematics_plugin_loader.so
(gdb) bt
#0  0x00007ffff62b8e2c in boost::detail::sp_counted_impl_p<kinematics::KinematicsBase>::dispose() () from /opt/ros/hydro/lib/libmoveit_kinematics_plugin_loader.so
#1  0x00007ffff6081a4a in moveit::core::JointModelGroup::KinematicsSolver::~KinematicsSolver() () from /opt/ros/hydro/lib/libmoveit_robot_model.so
#2  0x00007ffff6082ea7 in std::_Rb_tree<moveit::core::JointModelGroup const*, std::pair<moveit::core::JointModelGroup const* const, moveit::core::JointModelGroup::KinematicsSolver>, std::_Select1st<std::pair<moveit::core::JointModelGroup const* const, moveit::core::JointModelGroup::KinematicsSolver> >, std::less<moveit::core::JointModelGroup const*>, std::allocator<std::pair<moveit::core::JointModelGroup const* const, moveit::core::JointModelGroup::KinematicsSolver> > >::_M_erase(std::_Rb_tree_node<std::pair<moveit::core::JointModelGroup const* const, moveit::core::JointModelGroup::KinematicsSolver> >*) () from /opt/ros/hydro/lib/libmoveit_robot_model.so
#3  0x00007ffff607dd74 in moveit::core::JointModelGroup::~JointModelGroup() () from /opt/ros/hydro/lib/libmoveit_robot_model.so
#4  0x00007ffff608a6a1 in moveit::core::RobotModel::~RobotModel() () from /opt/ros/hydro/lib/libmoveit_robot_model.so
#5  0x00007ffff7bd42d2 in boost::detail::sp_counted_impl_p<moveit::core::RobotModel>::dispose() () from /opt/ros/hydro/lib/libmoveit_robot_model_loader.so
#6  0x0000000000407616 in boost::detail::sp_counted_base::release() ()
#7  0x000000000040768f in boost::detail::shared_count::~shared_count() ()
#8  0x00007ffff77501d9 in planning_scene::PlanningScene::~PlanningScene() () from /opt/ros/hydro/lib/libmoveit_planning_scene.so
#9  0x0000000000408fcd in void boost::checked_delete<planning_scene::PlanningScene>(planning_scene::PlanningScene*) ()
#10 0x00000000004091e0 in boost::detail::sp_counted_impl_p<planning_scene::PlanningScene>::dispose() ()
#11 0x0000000000407616 in boost::detail::sp_counted_base::release() ()
#12 0x000000000040768f in boost::detail::shared_count::~shared_count() ()
#13 0x0000000000408c0e in boost::shared_ptr<planning_scene::PlanningScene>::~shared_ptr() ()
#14 0x00000000004087be in shadowrobot::ShKinematics::~ShKinematics() ()
#15 0x0000000000406e9c in main ()
(gdb)
```
