### ISSUE TITLE
moveit_ros_move_group: linkedit error on OS X

### ISSUE THREAD

**Issue by wjwwood** [moveit/moveit_ros#259]
When building `moveit_ros_move_group` on OS X I get:

```
==> Processing catkin package: 'moveit_ros_move_group'
==> Creating build directory: 'build_isolated/moveit_ros_move_group'
==> Building with env: '/Users/william/moveit_ws/install_isolated/env.sh'
==> cmake /Users/william/moveit_ws/src/moveit_ros/move_group -DCATKIN_DEVEL_PREFIX=/Users/william/moveit_ws/devel_isolated/moveit_ros_move_group -DCMAKE_INSTALL_PREFIX=/Users/william/moveit_ws/install_isolated
-- The C compiler identification is Clang 4.2.0
-- The CXX compiler identification is Clang 4.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   program_options
--   signals
--   thread
-- Using CATKIN_DEVEL_PREFIX: /Users/william/moveit_ws/devel_isolated/moveit_ros_move_group
-- Using CMAKE_PREFIX_PATH: /Users/william/moveit_ws/install_isolated
-- This workspace overlays: /Users/william/moveit_ws/install_isolated
-- Found PythonInterp: /usr/bin/python (found version "2.7.2")
-- Found PY_em: /Library/Python/2.7/site-packages/em.pyc
-- Found gtest: gtests will be built
-- Using CATKIN_TEST_RESULTS_DIR: /Users/william/moveit_ws/build_isolated/moveit_ros_move_group/test_results
-- catkin 0.5.65
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/william/moveit_ws/build_isolated/moveit_ros_move_group
==> make -j4 -l4 in '/Users/william/moveit_ws/build_isolated/moveit_ros_move_group'
Scanning dependencies of target list_move_group_capabilities
Scanning dependencies of target moveit_move_group_default_capabilities
Scanning dependencies of target move_group
[  8%] Building CXX object CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o
[ 16%] [ 25%] Building CXX object CMakeFiles/move_group.dir/src/move_group_context.cpp.o
Building CXX object CMakeFiles/move_group.dir/src/move_group_capability.cpp.o
[ 33%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/move_action_capability.cpp.o
[ 41%] Building CXX object CMakeFiles/move_group.dir/src/move_group.cpp.o
Linking CXX executable /Users/william/moveit_ws/devel_isolated/moveit_ros_move_group/lib/moveit_ros_move_group/list_move_group_capabilities
[ 41%] Built target list_move_group_capabilities
[ 50%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/plan_service_capability.cpp.o
[ 58%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/execute_service_capability.cpp.o
Linking CXX executable /Users/william/moveit_ws/devel_isolated/moveit_ros_move_group/lib/moveit_ros_move_group/move_group
[ 58%] Built target move_group
[ 66%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/query_planners_service_capability.cpp.o
[ 75%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/kinematics_service_capability.cpp.o
[ 83%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/state_validation_service_capability.cpp.o
[ 91%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/cartesian_path_service_capability.cpp.o
[100%] Building CXX object CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/get_planning_scene_service_capability.cpp.o
Linking CXX shared library /Users/william/moveit_ws/devel_isolated/moveit_ros_move_group/lib/libmoveit_move_group_default_capabilities.dylib
Undefined symbols for architecture x86_64:
  "move_group::MoveGroupCapability::getActionResultString(moveit_msgs::MoveItErrorCodes_<std::allocator<void> > const&, bool, bool)", referenced from:
      move_group::MoveGroupMoveAction::executeMoveCallback(boost::shared_ptr<moveit_msgs::MoveGroupGoal_<std::allocator<void> > const> const&) in move_action_capability.cpp.o
  "move_group::MoveGroupCapability::stateToStr(move_group::MoveGroupState) const", referenced from:
      move_group::MoveGroupMoveAction::executeMoveCallback(boost::shared_ptr<moveit_msgs::MoveGroupGoal_<std::allocator<void> > const> const&) in move_action_capability.cpp.o
      move_group::MoveGroupMoveAction::setMoveState(move_group::MoveGroupState) in move_action_capability.cpp.o
      move_group::MoveGroupMoveAction::startMoveExecutionCallback() in move_action_capability.cpp.o
      move_group::MoveGroupMoveAction::planUsingPlanningPipeline(moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, plan_execution::ExecutableMotionPlan&) in move_action_capability.cpp.o
      move_group::MoveGroupMoveAction::startMoveLookCallback() in move_action_capability.cpp.o
  "move_group::MoveGroupCapability::convertToMsg(boost::shared_ptr<robot_trajectory::RobotTrajectory> const&, moveit_msgs::RobotState_<std::allocator<void> >&, moveit_msgs::RobotTrajectory_<std::allocator<void> >&) const", referenced from:
      move_group::MoveGroupMoveAction::executeMoveCallback_PlanOnly(boost::shared_ptr<moveit_msgs::MoveGroupGoal_<std::allocator<void> > const> const&, moveit_msgs::MoveGroupResult_<std::allocator<void> >&) in move_action_capability.cpp.o
  "move_group::MoveGroupCapability::convertToMsg(std::vector<plan_execution::ExecutableTrajectory, std::allocator<plan_execution::ExecutableTrajectory> > const&, moveit_msgs::RobotState_<std::allocator<void> >&, moveit_msgs::RobotTrajectory_<std::allocator<void> >&) const", referenced from:
      move_group::MoveGroupMoveAction::executeMoveCallback_PlanAndExecute(boost::shared_ptr<moveit_msgs::MoveGroupGoal_<std::allocator<void> > const> const&, moveit_msgs::MoveGroupResult_<std::allocator<void> >&) in move_action_capability.cpp.o
  "move_group::MoveGroupCapability::performTransform(geometry_msgs::PoseStamped_<std::allocator<void> >&, std::string const&) const", referenced from:
      move_group::MoveGroupKinematicsService::computeFKService(moveit_msgs::GetPositionFKRequest_<std::allocator<void> >&, moveit_msgs::GetPositionFKResponse_<std::allocator<void> >&) in kinematics_service_capability.cpp.o
      move_group::MoveGroupKinematicsService::computeIK(moveit_msgs::PositionIKRequest_<std::allocator<void> >&, moveit_msgs::RobotState_<std::allocator<void> >&, moveit_msgs::MoveItErrorCodes_<std::allocator<void> >&, boost::function<bool (robot_state::JointStateGroup*, std::vector<double, std::allocator<double> > const&)> const&) const in kinematics_service_capability.cpp.o
      move_group::MoveGroupCartesianPathService::computeService(moveit_msgs::GetCartesianPathRequest_<std::allocator<void> >&, moveit_msgs::GetCartesianPathResponse_<std::allocator<void> >&) in cartesian_path_service_capability.cpp.o
  "move_group::MoveGroupCapability::clearSceneRobotState(moveit_msgs::PlanningScene_<std::allocator<void> > const&) const", referenced from:
      move_group::MoveGroupMoveAction::executeMoveCallback_PlanAndExecute(boost::shared_ptr<moveit_msgs::MoveGroupGoal_<std::allocator<void> > const> const&, moveit_msgs::MoveGroupResult_<std::allocator<void> >&) in move_action_capability.cpp.o
  "move_group::MoveGroupCapability::clearRequestStartState(moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&) const", referenced from:
      move_group::MoveGroupMoveAction::executeMoveCallback_PlanAndExecute(boost::shared_ptr<moveit_msgs::MoveGroupGoal_<std::allocator<void> > const> const&, moveit_msgs::MoveGroupResult_<std::allocator<void> >&) in move_action_capability.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/william/moveit_ws/devel_isolated/moveit_ros_move_group/lib/libmoveit_move_group_default_capabilities.dylib] Error 1
make[1]: *** [CMakeFiles/moveit_move_group_default_capabilities.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "./src/catkin/bin/../python/catkin/builder.py", line 658, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "./src/catkin/bin/../python/catkin/builder.py", line 443, in build_package
    install, jobs, force_cmake, quiet, last_env, cmake_args, make_args
  File "./src/catkin/bin/../python/catkin/builder.py", line 297, in build_catkin_package
    run_command(make_cmd, build_dir, quiet)
  File "./src/catkin/bin/../python/catkin/builder.py", line 186, in run_command
    raise subprocess.CalledProcessError(proc.returncode, ' '.join(cmd))
CalledProcessError: Command '/Users/william/moveit_ws/install_isolated/env.sh make -j4 -l4' returned non-zero exit status 2
<== Failed to process package 'moveit_ros_move_group':
  Command '/Users/william/moveit_ws/install_isolated/env.sh make -j4 -l4' returned non-zero exit status 2

Reproduce this error by running:
==> /Users/william/moveit_ws/install_isolated/env.sh make -j4 -l4

Command failed, exiting.
```

**Comment by wjwwood** [comment]
The symbol `move_group::MoveGroupCapability::getActionResultString` is in `move_group_capability.h/cpp` which is only used as part of the `move_group` executable, but it looks like the `moveit_move_group_default_capabilities` library needs symbols from it.

I think the correct thing to do here is to build another library which both the `move_group` executable and the  `moveit_move_group_default_capabilities` library link against. I'm not sure how this works on Linux...

**Comment by wjwwood** [comment]
Adding the `src/move_group_capability.cpp` file to the `moveit_move_group_default_capabilities` library target works also. Do you have preference on the fix?
