### ISSUE TITLE
Segfault on shutdown when using Motion Planning RVIZ plugin

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#458]
When using the Motion Planning plugin in RVIZ on Indigo/14.04 (from debs), I get a segfault when exiting RVIZ:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fff5f436d40 in void boost::checked_delete<kinematics::KinematicsBase>(kinematics::KinematicsBase*) ()
   from /opt/ros/indigo/lib/libmoveit_kinematics_plugin_loader.so
(gdb) bt
#0  0x00007fff5f436d40 in void boost::checked_delete<kinematics::KinematicsBase>(kinematics::KinematicsBase*) ()
   from /opt/ros/indigo/lib/libmoveit_kinematics_plugin_loader.so
#1  0x00007fff5f43d922 in boost::detail::sp_counted_impl_p<kinematics::KinematicsBase>::dispose() ()
   from /opt/ros/indigo/lib/libmoveit_kinematics_plugin_loader.so
#2  0x00007ffff79ba258 in boost::detail::sp_counted_base::release() () from /opt/ros/indigo/lib/librviz.so
#3  0x00007ffff79ba2e7 in boost::detail::shared_count::~shared_count() () from /opt/ros/indigo/lib/librviz.so
#4  0x00007fff6511d0ea in boost::shared_ptr<kinematics::KinematicsBase const>::~shared_ptr() ()
   from /opt/ros/indigo/lib/libmoveit_robot_model.so
#5  0x00007fff6511d4df in moveit::core::JointModelGroup::KinematicsSolver::~KinematicsSolver() ()
   from /opt/ros/indigo/lib/libmoveit_robot_model.so
#6  0x00007fff6511d58b in std::pair<moveit::core::JointModelGroup::KinematicsSolver, std::map<moveit::core::JointModelGroup const*, moveit::core::JointModelGroup::KinematicsSolver, std::less<moveit::core::JointModelGroup const*>, std::allocator<std::pair<moveit::core::JointModelGroup const* const, moveit::core::JointModelGroup::KinematicsSolver> > > >::~pair()
    () from /opt/ros/indigo/lib/libmoveit_robot_model.so
#7  0x00007fff65117f67 in moveit::core::JointModelGroup::~JointModelGroup() ()
   from /opt/ros/indigo/lib/libmoveit_robot_model.so
#8  0x00007fff6512e2ce in moveit::core::RobotModel::~RobotModel() () from /opt/ros/indigo/lib/libmoveit_robot_model.so
#9  0x00007fff63fe13a8 in void boost::checked_delete<moveit::core::RobotModel>(moveit::core::RobotModel*) ()
   from /opt/ros/indigo/lib/libmoveit_planning_scene.so
#10 0x00007fff6400a912 in boost::detail::sp_counted_impl_p<moveit::core::RobotModel>::dispose() ()
   from /opt/ros/indigo/lib/libmoveit_planning_scene.so
#11 0x00007ffff79ba258 in boost::detail::sp_counted_base::release() () from /opt/ros/indigo/lib/librviz.so
#12 0x00007ffff79ba2e7 in boost::detail::shared_count::~shared_count() () from /opt/ros/indigo/lib/librviz.so
#13 0x00007fff675bce2c in boost::shared_ptr<moveit::core::RobotModel const>::~shared_ptr() ()
   from /opt/ros/indigo/lib/libmoveit_motion_planning_rviz_plugin_core.so
#14 0x00007fff65bdf8df in planning_scene_monitor::CurrentStateMonitor::~CurrentStateMonitor() ()
   from /opt/ros/indigo/lib/libmoveit_planning_scene_monitor.so
#15 0x00007fff65b86318 in void boost::checked_delete<planning_scene_monitor::CurrentStateMonitor>(planning_scene_monitor::CurrentStateMonitor*) () from /opt/ros/indigo/lib/libmoveit_planning_scene_monitor.so
#16 0x00007fff65bd1500 in boost::detail::sp_counted_impl_p<planning_scene_monitor::CurrentStateMonitor>::dispose() ()
   from /opt/ros/indigo/lib/libmoveit_planning_scene_monitor.so
#17 0x00007ffff79ba258 in boost::detail::sp_counted_base::release() () from /opt/ros/indigo/lib/librviz.so
#18 0x00007ffff79ba2e7 in boost::detail::shared_count::~shared_count() () from /opt/ros/indigo/lib/librviz.so
#19 0x00007fff66810e0a in boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor>::~shared_ptr() ()
   from /opt/ros/indigo/lib/libmoveit_move_group_interface.so
#20 0x00007fff62a89063 in std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> >::~pair() () from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#21 0x00007fff62a8b4b6 in __gnu_cxx::new_allocator<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > >::destroy(std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> >*) () from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#22 0x00007fff62a8ab66 in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> >, std::_Select1st<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > >, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > > >::_M_destroy_node(std::_Rb_tree_node<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > >*) ()
   from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#23 0x00007fff62a89dab in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<planning_scene_monito---Type <return> to continue, or q <return> to quit---
r::CurrentStateMonitor> >, std::_Select1st<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > >, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > >*) () from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#24 0x00007fff62a89e39 in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> >, std::_Select1st<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > >, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > > >::clear() () from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#25 0x00007fff62a88b34 in std::map<std::string, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor>, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<planning_scene_monitor::CurrentStateMonitor> > > >::clear() () from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#26 0x00007fff62a86069 in ?? () from /opt/ros/indigo/lib/libmoveit_common_planning_interface_objects.so
#27 0x00007ffff6245509 in __run_exit_handlers (status=0, listp=0x7ffff65c86c8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#28 0x00007ffff6245555 in __GI_exit (status=<optimized out>) at exit.c:104
#29 0x00007ffff622aecc in __libc_start_main (main=0x40105d <main>, argc=1, argv=0x7fffffffdb08, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdaf8) at libc-start.c:321
#30 0x0000000000400f99 in _start ()

```

**Comment by mikeferguson** [comment]
This is no longer reproducible, so must have been fixed somewhere along the way.
