### ISSUE TITLE
problem with joystick_control.launch

### ISSUE THREAD

**Issue by RockOn23** [moveit/moveit_ros#637]
I want to jog an industrial 6-axis robot in MoveIt/ rviz via a xbox 360 wireless controller.

I have created a MoveIt package as described here and started the demo.launch. Next, I installed MoveIt from source in the workspace and followed this instruction to start the joystick_control.launch.

Starting joystick_control.launch leads to

```
benjamin@benjamin:~/Desktop/my_irb120$ roslaunch my_abb_irb120_moveit_config joystick_control.launch 
... logging to /home/benjamin/.ros/log/77f2bc80-bd59-11e5-979d-8c2937e5b4fe/roslaunch-benjamin-4916.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://benjamin:38469/

SUMMARY
========

PARAMETERS
 * /joy/autorepeat_rate: 40
 * /joy/coalesce_interval: 0.025
 * /joy/deadzone: 0.2
 * /joy/dev: /dev/input/js0
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    joy (joy/joy_node)
    moveit_joy (moveit_ros_visualization/moveit_joy.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[joy-1]: started with pid [4934]
process[moveit_joy-2]: started with pid [4939]
[ INFO] [1453063159.797560585]: Loading robot model 'abb_irb120'...
[ INFO] [1453063160.694999145]: Loading robot model 'abb_irb120'...
[ WARN] [1453063161.297892190]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
Traceback (most recent call last):
  File "/home/benjamin/Desktop/my_irb120/src/moveit_ros/visualization/python/moveit_ros_visualization/moveit_joy.py", line 609, in <module>
    app = MoveitJoy()
  File "/home/benjamin/Desktop/my_irb120/src/moveit_ros/visualization/python/moveit_ros_visualization/moveit_joy.py", line 380, in __init__
    self.updatePlanningGroup(0)
  File "/home/benjamin/Desktop/my_irb120/src/moveit_ros/visualization/python/moveit_ros_visualization/moveit_joy.py", line 398, in updatePlanningGroup
    next_planning_group = self.planning_groups_keys[self.current_planning_group_index]
IndexError: list index out of range
terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
  what():  Attempt to unload library that class_loader is unaware of.
[moveit_joy-2] process has died [pid 4939, exit code -6, cmd /home/benjamin/Desktop/my_irb120/src/moveit_ros/visualization/python/moveit_ros_visualization/moveit_joy.py __name:=moveit_joy __log:=/home/benjamin/.ros/log/77f2bc80-bd59-11e5-979d-8c2937e5b4fe/moveit_joy-2.log].
log file: /home/benjamin/.ros/log/77f2bc80-bd59-11e5-979d-8c2937e5b4fe/moveit_joy-2*.log
```

Also asked here: http://answers.ros.org/question/223398/problem-with-moveit-rviz-joystick_controllaunch/

**Comment by 130s** [comment]
[As I posted](http://answers.ros.org/question/223398/problem-with-moveit-rviz-joystick_controllaunch/?answer=224547#post-id-224547) the cause is likely that there's no move group running. I'm making a patch for friendlier error handling.
